Repository TheSixthSense/app-ios, pull requests merged in 2022-08, with the labels that each got.

#60 [APP] 회원가입 API를 연결해요
  SixthSense/Account/Sources/SignIn/Presentation/SignInBuilder.swift
  SixthSense/Account/Sources/SignUp/Domain/UseCases/SignUpUseCase.swift
  SixthSense/Account/Sources/SignUp/Presentation/SignUpBuilder.swift
  SixthSense/Account/Sources/SignUp/Presentation/SignUpInteractor.swift
  SixthSense/Account/Sources/SignUp/Presentation/SignUpViewController.swift
  SixthSense/Account/Sources/SignUp/Presentation/SubViews/SignUpPageViewController.swift
  SixthSense/Repository/Sources/User/Requests/SignUpRequest.swift
  SixthSense/Repository/Sources/User/UserAPI.swift
  SixthSense/Repository/Sources/User/UserRepository.swift
  SixthSense/Repository/Sources/User/UserRepositoryImpl.swift
Labels: :sparkles: enhancement

#62 [APP] `SignUpRIB`에 에러 메세지를 추가했어요
  SixthSense/Account/Sources/SignUp/Domain/UseCases/SignUpUseCase.swift
  SixthSense/Account/Sources/SignUp/Presentation/SignUpInteractor.swift
  SixthSense/Account/Sources/SignUp/Presentation/SignUpViewController.swift
  SixthSense/Account/Sources/SignUp/Presentation/SubViews/BirthStepViewController.swift
  SixthSense/Account/Sources/SignUp/Presentation/SubViews/NicknameStepViewController.swift
  SixthSense/Account/Sources/SignUp/Presentation/SubViews/SignUpPageViewController.swift
  SixthSense/DesignSystem/Sources/AppTextField.swift
Labels: :sparkles: enhancement, :hammer: refactor

#63 [App] 홈 모듈을 구성하고 ChildViewController를 구성했어요
  .gitignore
  SixthSense/Home/Project.swift
  SixthSense/Home/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  SixthSense/Home/Resources/Assets.xcassets/Contents.json
  SixthSense/Home/Resources/Assets.xcassets/탭바/Contents.json
  SixthSense/Home/Resources/Assets.xcassets/탭바/feedTabBarIcon_unselected.imageset/Contents.json
  SixthSense/Home/Resources/Assets.xcassets/탭바/feedTabBarIcon_unselected.imageset/feedTabBarIcon.svg
  SixthSense/Home/Resources/Assets.xcassets/탭바/homeTabBarIcon.imageset/Contents.json
  SixthSense/Home/Resources/Assets.xcassets/탭바/homeTabBarIcon.imageset/homeTabBarIcon.svg
  SixthSense/Home/Sources/ChallengeCalendar/ChallengeCalendarBuilder.swift
  SixthSense/Home/Sources/ChallengeCalendar/ChallengeCalendarInteractor.swift
  SixthSense/Home/Sources/ChallengeCalendar/ChallengeCalendarRouter.swift
  SixthSense/Home/Sources/ChallengeCalendar/ChallengeCalendarViewController.swift
  SixthSense/Home/Sources/ChallengeList/ChallengeListBuilder.swift
  SixthSense/Home/Sources/ChallengeList/ChallengeListInteractor.swift
  SixthSense/Home/Sources/ChallengeList/ChallengeListRouter.swift
  SixthSense/Home/Sources/ChallengeList/ChallengeListViewController.swift
  SixthSense/Home/Sources/Extensions/Array+.swift
  SixthSense/Home/Sources/Extensions/UI/UIStackView+.swift
  SixthSense/Home/Sources/Extensions/UI/UIView+.swift
  SixthSense/Home/Sources/Extensions/ViewControllable+Utils.swift
  SixthSense/Splash/Project.swift
  SixthSense/Tuist/ProjectDescriptionHelpers/ProjectName.swift
Labels: :sparkles: enhancement

#65 [App] `SignIn`, `Splash`, `Home` Riblet을 `Root`하위 수평관계로 변경하였어요
  SixthSense/Account/Sources/SignIn/Presentation/SignInInteractor.swift
  SixthSense/Splash/Sources/SplashRIB/SplashBuilder.swift
  SixthSense/Splash/Sources/SplashRIB/SplashInteractor.swift
  SixthSense/Splash/Sources/SplashRIB/SplashRouter.swift
  SixthSense/VegannerApp/Sources/Root/RootRIB/RootBuilder.swift
  SixthSense/VegannerApp/Sources/Root/RootRIB/RootComponent+Splash.swift
  SixthSense/VegannerApp/Sources/Root/RootRIB/RootComponent.swift
  SixthSense/VegannerApp/Sources/Root/RootRIB/RootInteractor.swift
  SixthSense/VegannerApp/Sources/Root/RootRIB/RootRouter.swift
Labels: :sparkles: enhancement

#66 [App] 챌린지 | 챌린지 달력 화면 UI를 구성하였어요
  SixthSense/DesignSystem/Resources/Assets.xcassets/chevronDown.imageset/Contents.json
  SixthSense/DesignSystem/Resources/Assets.xcassets/chevronDown.imageset/chevronDown.svg
  SixthSense/DesignSystem/Resources/Assets.xcassets/plus.imageset/Contents.json
  SixthSense/DesignSystem/Resources/Assets.xcassets/plus.imageset/plus.svg
  SixthSense/Home/Project.swift
  SixthSense/Home/Sources/Challenge/ChallengeViewController.swift
  SixthSense/Home/Sources/ChallengeCalendar/ChallengeCalendarViewController.swift
  SixthSense/Home/Sources/ChallengeCalendar/Views/CalendarDayCell.swift
  SixthSense/Home/Sources/ChallengeCalendar/Views/CalendarHeaderView.swift
  SixthSense/Home/Sources/ChallengeCalendar/Views/CalendarWeekdayView.swift
  SixthSense/Home/Sources/Extensions/JTACMonthView+.swift
  SixthSense/Home/Sources/Extensions/UI/UIStackView+.swift
  SixthSense/Home/Sources/Extensions/UICollectionView+.swift
  SixthSense/Tuist/Dependencies.swift
  SixthSense/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: :sparkles: enhancement, :art: UI

#67 [App] 챌린지 | 챌린지 리스트를 구성하였어요
  SixthSense/Home/Project.swift
  SixthSense/Home/Resources/Assets.xcassets/챌린지리스트/Contents.json
  SixthSense/Home/Resources/Assets.xcassets/챌린지리스트/vegetable.imageset/Contents.json
  SixthSense/Home/Resources/Assets.xcassets/챌린지리스트/vegetable.imageset/vegetable.svg
  SixthSense/Home/Resources/Assets.xcassets/챌린지캘린더/Contents.json
  SixthSense/Home/Resources/Assets.xcassets/챌린지캘린더/challenge_day_empty.imageset/Contents.json
  SixthSense/Home/Resources/Assets.xcassets/챌린지캘린더/challenge_day_empty.imageset/challenge_day_empty.svg
  SixthSense/Home/Sources/Challenge/ChallengeViewController.swift
  SixthSense/Home/Sources/ChallengeList/ChallengeListInteractor.swift
  SixthSense/Home/Sources/ChallengeList/ChallengeListViewController.swift
  SixthSense/Home/Sources/ChallengeList/ChallengeSection.swift
  SixthSense/Home/Sources/ChallengeList/Views/ChallengeItemCell.swift
  SixthSense/Home/Sources/Extensions/UICollectionView+.swift
  SixthSense/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: :sparkles: enhancement, :art: UI

#69 [APP] `SignUpRIB`과 `SignInRIB`을 연결하고, 뒤로가기 시 `detach`가 되지 않는 에러를 수정했어요.
  SixthSense/Account/Sources/Extensions/ViewControllable+Utils.swift
  SixthSense/Account/Sources/SignIn/Presentation/SignInInteractor.swift
  SixthSense/Account/Sources/SignIn/Presentation/SignInRouter.swift
  SixthSense/Account/Sources/SignUp/Presentation/SignUpInteractor.swift
  SixthSense/Account/Sources/SignUp/Presentation/SignUpViewController.swift
  SixthSense/Account/Sources/SignUp/Presentation/SubViews/BirthStepViewController.swift
Labels: :bug: bugfix

#72 [Design] Toast UI를 구현했어요
  SixthSense/DesignSystem/Sources/AppToast.swift
Labels: :art: UI

#75 [App] 홈 | 챌린지 캘린더와 년/월 선택 기능을 구현하였어요
  SixthSense/Home/Sources/ChallengeCalendar/CalendarConfigure.swift
  SixthSense/Home/Sources/ChallengeCalendar/ChallengeCalendarInteractor.swift
  SixthSense/Home/Sources/ChallengeCalendar/ChallengeCalendarViewController+Calendar.swift
  SixthSense/Home/Sources/ChallengeCalendar/ChallengeCalendarViewController.swift
  SixthSense/Home/Sources/ChallengeCalendar/Views/CalendarDayCell.swift
  SixthSense/Home/Sources/ChallengeCalendar/Views/CalendarHeaderView.swift
  SixthSense/Home/Sources/ChallengeList/ChallengeListInteractor.swift
  SixthSense/Home/Sources/ChallengeList/ChallengeListViewController.swift
  SixthSense/Home/Sources/ChallengeList/Views/ChallengeItemCell.swift
Labels: :sparkles: enhancement, :art: UI

#78 [App] 변경된 디자인으로 달력UI를 수정하고 날짜 챌린지 상태 값을 바인딩하는 로직을 추가했어요
  SixthSense/Home/Resources/Assets.xcassets/챌린지캘린더/challenge_day_almost.imageset/Contents.json
  SixthSense/Home/Resources/Assets.xcassets/챌린지캘린더/challenge_day_almost.imageset/challenge_day_almost.svg
  SixthSense/Home/Resources/Assets.xcassets/챌린지캘린더/challenge_day_done.imageset/Contents.json
  SixthSense/Home/Resources/Assets.xcassets/챌린지캘린더/challenge_day_done.imageset/challenge_day_done.svg
  SixthSense/Home/Resources/Assets.xcassets/챌린지캘린더/challenge_day_empty.imageset/challenge_day_empty.svg
  SixthSense/Home/Resources/Assets.xcassets/챌린지캘린더/challenge_day_over_zero.imageset/Contents.json
  SixthSense/Home/Resources/Assets.xcassets/챌린지캘린더/challenge_day_over_zero.imageset/overZero.svg
  SixthSense/Home/Resources/Assets.xcassets/챌린지캘린더/challenge_day_waiting.imageset/Contents.json
  SixthSense/Home/Resources/Assets.xcassets/챌린지캘린더/challenge_day_waiting.imageset/challenge_day_waiting.svg
  SixthSense/Home/Resources/Assets.xcassets/챌린지캘린더/challenge_day_zero.imageset/Contents.json
  SixthSense/Home/Resources/Assets.xcassets/챌린지캘린더/challenge_day_zero.imageset/challenge_day_zero.svg
  SixthSense/Home/Resources/Assets.xcassets/챌린지캘린더/challenge_today_waiting.imageset/Contents.json
  SixthSense/Home/Resources/Assets.xcassets/챌린지캘린더/challenge_today_waiting.imageset/challenge_today_waiting.svg
  SixthSense/Home/Sources/ChallengeCalendar/ChallengeCalendarDayState.swift
  SixthSense/Home/Sources/ChallengeCalendar/ChallengeCalendarInteractor.swift
  SixthSense/Home/Sources/ChallengeCalendar/ChallengeCalendarViewController+Calendar.swift
  SixthSense/Home/Sources/ChallengeCalendar/ChallengeCalendarViewController.swift
  SixthSense/Home/Sources/ChallengeCalendar/Views/CalendarDayCell.swift
Labels: :sparkles: enhancement, :art: UI

#79 [App] 캘린더-리스트 간 글로벌 스트림을 구성하고 날짜 선택 시 리스트 패치를 돌리는 로직을 구성했어요
  SixthSense/Home/Sources/Challenge/ChallengeBuilder.swift
  SixthSense/Home/Sources/ChallengeCalendar/ChallengeCalendarBuilder.swift
  SixthSense/Home/Sources/ChallengeCalendar/ChallengeCalendarInteractor.swift
  SixthSense/Home/Sources/ChallengeCalendar/ChallengeCalendarViewController+Calendar.swift
  SixthSense/Home/Sources/ChallengeCalendar/ChallengeCalendarViewController.swift
  SixthSense/Home/Sources/ChallengeList/ChallengeListBuilder.swift
  SixthSense/Home/Sources/ChallengeList/ChallengeListInteractor.swift
Labels: :sparkles: enhancement, :eyes: dependent

#84 [App] 홈 | 챌린지 리스트 상태별 아이템을 구성하고 오늘날짜 이후에만 챌린지 추가하기 버튼이 나오도록 변경했어요
  SixthSense/Home/Resources/Assets.xcassets/챌린지리스트/challenge_add.imageset/Contents.json
  SixthSense/Home/Resources/Assets.xcassets/챌린지리스트/challenge_add.imageset/challenge_add.svg
  SixthSense/Home/Sources/ChallengeList/ChallengeListInteractor.swift
  SixthSense/Home/Sources/ChallengeList/ChallengeListViewController.swift
  SixthSense/Home/Sources/ChallengeList/ChallengeSection.swift
  SixthSense/Home/Sources/ChallengeList/Views/ChallengeAddCell.swift
  SixthSense/Home/Sources/ChallengeList/Views/ChallengeFailedItemCell.swift
  SixthSense/Home/Sources/ChallengeList/Views/ChallengeItemCell.swift
  SixthSense/Home/Sources/ChallengeList/Views/ChallengeItemCellViewModel.swift
  SixthSense/Home/Sources/ChallengeList/Views/ChallengeSuccessItemCell.swift
  SixthSense/Home/Sources/ChallengeList/Views/ChallengeWaitingItemCell.swift
Labels: :sparkles: enhancement, :art: UI

#85 [FIX] 빌드 오류를 수정해요
  .gitignore
  SixthSense/Challenge/Sources/ChallengeRegister/ChallengeRegisterBuilder.swift
  SixthSense/Challenge/Sources/ChallengeRegister/ChallengeRegisterInteractor.swift
  SixthSense/Challenge/Sources/ChallengeRegister/ChallengeRegisterRouter.swift
  SixthSense/Challenge/Sources/ChallengeRegister/ChallengeRegisterViewController.swift
Labels: :broom: chore

#87 [App] 홈 | 캘린더 빌드 오류 수정
  SixthSense/Home/Sources/ChallengeCalendar/ChallengeCalendarViewController.swift
  SixthSense/Home/Sources/ChallengeCalendar/Views/CalendarHeaderView.swift
Labels: :bug: bugfix

#93 [Network] AccessToken 로직을 추가했어요
  SixthSense/Repository/Sources/Network/Plugins/AccessTokenPlugin.swift
  SixthSense/Repository/Sources/User/UserAPI.swift
  SixthSense/VegannerApp/Sources/App/AppComponent.swift
Labels: :bug: bugfix, :sparkles: enhancement

#91 [Challenge] 챌린지 등록 화면을 수정했어요
  SixthSense/Challenge/Sources/ChallengeRecommend/Presentation/RIB/ChallengeRecommendViewController.swift
  SixthSense/DesignSystem/Sources/Assets/AppIcon.swift
  SixthSense/Home/Sources/ChallengeCalendar/CalendarConfigure.swift
  SixthSense/Home/Sources/ChallengeRegister/Cell/ChallengeListDescriptionCell.swift
  SixthSense/Home/Sources/ChallengeRegister/Cell/ChallengeListItemCell.swift
  SixthSense/Home/Sources/ChallengeRegister/DataSource/ChallengeListCellViewModel.swift
  SixthSense/Home/Sources/ChallengeRegister/DataSource/ChallengeListSection.swift
  SixthSense/Home/Sources/ChallengeRegister/Domain/ChallengeRegisterUseCase.swift
  SixthSense/Home/Sources/ChallengeRegister/RIB/ChallengeRegisterBuilder.swift
  SixthSense/Home/Sources/ChallengeRegister/RIB/ChallengeRegisterInteractor.swift
  SixthSense/Home/Sources/ChallengeRegister/RIB/ChallengeRegisterViewController.swift
  SixthSense/Home/Sources/Extensions/UICollectionView+.swift
  SixthSense/Home/Sources/Home/HomeBuilder.swift
  SixthSense/Home/Sources/Home/HomeComponent.swift
  SixthSense/Repository/Sources/Challnege/ChallengeAPI.swift
  SixthSense/Repository/Sources/Challnege/ChallengeRepository.swift
  SixthSense/Repository/Sources/Challnege/ChallengeRepositoryImpl.swift
  SixthSense/Splash/Sources/SplashRIB/SplashBuilder.swift
  SixthSense/VegannerApp/Sources/App/AppComponent.swift
  SixthSense/VegannerApp/Sources/Root/RootRIB/RootBuilder.swift
  SixthSense/VegannerApp/Sources/Root/RootRIB/RootComponent.swift
Labels: :sparkles: enhancement, :eyes: dependent

#94 [UICore] 팝업을 만들었어요
  SixthSense/Home/Project.swift
  SixthSense/Home/Resources/Assets.xcassets/탭바/challengeRegistericon_unselected.imageset/Contents.json
  SixthSense/Tuist/ProjectDescriptionHelpers/ProjectName.swift
  SixthSense/UICore/Project.swift
  SixthSense/UICore/Sources/Alert/AlertAction.swift
  SixthSense/UICore/Sources/Alert/AppAlertView.swift
  SixthSense/UICore/Sources/Extension/UIStackView+.swift
  SixthSense/UICore/Sources/Extension/UIView+.swift
  SixthSense/UICore/Sources/Extension/UIWindow+.swift
  SixthSense/UICore/Sources/Toast/AppToast.swift
Labels: :art: UI

#99 [APP] 챌린지 등록 리스트 API를 연결했어요
  SixthSense/Challenge/Sources/ChallengeRecommend/Presentation/RIB/ChallengeRecommendInteractor.swift
  SixthSense/Challenge/Sources/ChallengeRecommend/Presentation/RIB/ChallengeRecommendViewController.swift
  SixthSense/Home/Sources/Challenge/ChallengeViewController.swift
  SixthSense/Home/Sources/ChallengeRegister/Cell/CategoryTabItemCell.swift
  SixthSense/Home/Sources/ChallengeRegister/Cell/ChallengeListDescriptionCell.swift
  SixthSense/Home/Sources/ChallengeRegister/Cell/ChallengeListItemCell.swift
  SixthSense/Home/Sources/ChallengeRegister/DataSource/CategorySection.swift
  SixthSense/Home/Sources/ChallengeRegister/DataSource/ChallengeListCellViewModel.swift
  SixthSense/Home/Sources/ChallengeRegister/DataSource/ChallengeListSection.swift
  SixthSense/Home/Sources/ChallengeRegister/DataSource/ViewModel/CategoryCellViewModel.swift
  SixthSense/Home/Sources/ChallengeRegister/DataSource/ViewModel/ChallengeListCellViewModel.swift
  SixthSense/Home/Sources/ChallengeRegister/DataSource/ViewModel/DataViewModel.swift
  SixthSense/Home/Sources/ChallengeRegister/Domain/UseCases/ChallengeRegisterUseCase.swift
  SixthSense/Home/Sources/ChallengeRegister/RIB/ChallengeRegisterBuilder.swift
  SixthSense/Home/Sources/ChallengeRegister/RIB/ChallengeRegisterInteractor.swift
  SixthSense/Home/Sources/ChallengeRegister/RIB/ChallengeRegisterRouter.swift
  SixthSense/Home/Sources/ChallengeRegister/RIB/ChallengeRegisterViewController.swift
  SixthSense/Home/Sources/Extensions/ViewControllable+Utils.swift
  SixthSense/Repository/Sources/Challnege/ChallengeAPI.swift
  SixthSense/Repository/Sources/Challnege/ChallengeRepository.swift
  SixthSense/Repository/Sources/Challnege/ChallengeRepositoryImpl.swift
Labels: :sparkles: enhancement, :eyes: dependent

#97 [APP] 회원가입 API 에러 핸들링을 적용했어요
  SixthSense/Account/Sources/SignIn/Presentation/SignInInteractor.swift
  SixthSense/Account/Sources/SignIn/Presentation/SignInRouter.swift
  SixthSense/Account/Sources/SignUp/Presentation/SignUpInteractor.swift
  SixthSense/Account/Sources/SignUp/Presentation/SignUpViewController.swift
  SixthSense/Challenge/Sources/ChallengeRecommend/Presentation/RIB/ChallengeRecommendInteractor.swift
  SixthSense/Challenge/Sources/ChallengeRecommend/Presentation/RIB/ChallengeRecommendViewController.swift
  SixthSense/Home/Resources/Assets.xcassets/탭바/challengeRegisterTabBarIcon_unselected.imageset/Contents.json
  SixthSense/Home/Resources/Assets.xcassets/탭바/challengeRegisterTabBarIcon_unselected.imageset/challengeRegisterTabBarIcon_unselected.svg
  SixthSense/Home/Resources/Assets.xcassets/탭바/challengeRegistericon_unselected.imageset/challengeRegistericon.svg
  SixthSense/Home/Sources/Challenge/ChallengeViewController.swift
  SixthSense/Home/Sources/ChallengeRegister/Cell/CategoryTabItemCell.swift
  SixthSense/Home/Sources/ChallengeRegister/Cell/ChallengeListDescriptionCell.swift
  SixthSense/Home/Sources/ChallengeRegister/Cell/ChallengeListItemCell.swift
  SixthSense/Home/Sources/ChallengeRegister/DataSource/CategorySection.swift
  SixthSense/Home/Sources/ChallengeRegister/DataSource/ChallengeListCellViewModel.swift
  SixthSense/Home/Sources/ChallengeRegister/DataSource/ChallengeListSection.swift
  SixthSense/Home/Sources/ChallengeRegister/DataSource/ViewModel/CategoryCellViewModel.swift
  SixthSense/Home/Sources/ChallengeRegister/DataSource/ViewModel/ChallengeListCellViewModel.swift
  SixthSense/Home/Sources/ChallengeRegister/DataSource/ViewModel/DataViewModel.swift
  SixthSense/Home/Sources/ChallengeRegister/Domain/UseCases/ChallengeRegisterUseCase.swift
  SixthSense/Home/Sources/ChallengeRegister/RIB/ChallengeRegisterBuilder.swift
  SixthSense/Home/Sources/ChallengeRegister/RIB/ChallengeRegisterInteractor.swift
  SixthSense/Home/Sources/ChallengeRegister/RIB/ChallengeRegisterRouter.swift
  SixthSense/Home/Sources/ChallengeRegister/RIB/ChallengeRegisterViewController.swift
  SixthSense/Home/Sources/Extensions/ViewControllable+Utils.swift
  SixthSense/Repository/Sources/Challnege/ChallengeAPI.swift
  SixthSense/Repository/Sources/Challnege/ChallengeRepository.swift
  SixthSense/Repository/Sources/Challnege/ChallengeRepositoryImpl.swift
  SixthSense/Repository/Sources/Network/APIError.swift
  SixthSense/Repository/Sources/Network/ErrorResponse.swift
  SixthSense/Repository/Sources/Network/NetworkImpl.swift
  SixthSense/Repository/Sources/User/UserRepositoryImpl.swift
Labels: :sparkles: enhancement, :hammer: refactor

#106 [Challenge] 챌린지 등록 API를 연결했어요
  SixthSense/Home/Sources/ChallengeRegister/Domain/UseCases/ChallengeRegisterUseCase.swift
  SixthSense/Home/Sources/ChallengeRegister/RIB/ChallengeRegisterInteractor.swift
  SixthSense/Repository/Sources/Challnege/ChallengeAPI.swift
  SixthSense/Repository/Sources/Challnege/ChallengeRepository.swift
  SixthSense/Repository/Sources/Challnege/ChallengeRepositoryImpl.swift
  SixthSense/Repository/Sources/Challnege/Requests/ChallengeJoinRequest.swift
  SixthSense/Repository/Sources/User/Requests/SignUpRequest.swift
Labels: :sparkles: enhancement, :eyes: dependent

#103 [Challenge] ChallengeRegister/ChallengeRecommend API를 연결해요
  SixthSense/Challenge/Project.swift
  SixthSense/Challenge/Sources/ChallengeRecommend/Domain/Entities/ChallengeRecommendModel.swift
  SixthSense/Challenge/Sources/ChallengeRecommend/Domain/UseCases/ChallengeRecommendUseCase.swift
  SixthSense/Challenge/Sources/ChallengeRecommend/Presentation/Cell/RecommendItemCell.swift
  SixthSense/Challenge/Sources/ChallengeRecommend/Presentation/DataSource/RecommendSection.swift
  SixthSense/Challenge/Sources/ChallengeRecommend/Presentation/DataSource/RecommendViewModel.swift
  SixthSense/Challenge/Sources/ChallengeRecommend/Presentation/RIB/ChallengeRecommendBuilder.swift
  SixthSense/Challenge/Sources/ChallengeRecommend/Presentation/RIB/ChallengeRecommendInteractor.swift
  SixthSense/Challenge/Sources/ChallengeRecommend/Presentation/RIB/ChallengeRecommendViewController.swift
  SixthSense/Challenge/Sources/Extensions/UI/UIImageView+Kingfisher.swift
  SixthSense/Challenge/Sources/Extensions/UI/ViewControllable+Utils.swift
  SixthSense/Home/Sources/ChallengeRegister/DataSource/CategorySection.swift
  SixthSense/Home/Sources/ChallengeRegister/DataSource/ChallengeListSection.swift
  SixthSense/Home/Sources/ChallengeRegister/DataSource/ViewModel/CategoryCellViewModel.swift
  SixthSense/Home/Sources/ChallengeRegister/DataSource/ViewModel/ChallengeListCellViewModel.swift
  SixthSense/Home/Sources/ChallengeRegister/Domain/Entities/CategoryModel.swift
  SixthSense/Home/Sources/ChallengeRegister/Domain/Entities/ChallengeRegisterModel.swift
  SixthSense/Home/Sources/ChallengeRegister/Domain/Entities/DataModel.swift
  SixthSense/Home/Sources/ChallengeRegister/Domain/UseCases/ChallengeRegisterUseCase.swift
  SixthSense/Home/Sources/ChallengeRegister/RIB/ChallengeRegisterInteractor.swift
  SixthSense/Home/Sources/ChallengeRegister/RIB/ChallengeRegisterRouter.swift
  SixthSense/Home/Sources/ChallengeRegister/RIB/ChallengeRegisterViewController.swift
  SixthSense/Repository/Sources/Challnege/ChallengeAPI.swift
  SixthSense/Repository/Sources/Challnege/ChallengeRepository.swift
  SixthSense/Repository/Sources/Challnege/ChallengeRepositoryImpl.swift
  SixthSense/Repository/Sources/Challnege/Requests/ChallengeJoinRequest.swift
  SixthSense/Repository/Sources/Network/APIError.swift
  SixthSense/Repository/Sources/Network/ErrorResponse.swift
  SixthSense/Repository/Sources/User/Requests/SignUpRequest.swift
  SixthSense/Tuist/Dependencies.swift
Labels: :sparkles: enhancement
