Repository TheSixthSense/app-ios, pull requests merged in 2022-09, with the labels that each got.

#108 [App] 마이페이지 화면을 작성했어요
  SixthSense/Challenge/Sources/Extensions/UI/UIImageView+Kingfisher.swift
  SixthSense/DesignSystem/Sources/Assets/AppIcon.swift
  SixthSense/Home/Resources/Assets.xcassets/마이페이지/Contents.json
  SixthSense/Home/Resources/Assets.xcassets/마이페이지/profile_image.imageset/Contents.json
  SixthSense/Home/Resources/Assets.xcassets/마이페이지/profile_image.imageset/profile_image.svg
  SixthSense/Home/Resources/Assets.xcassets/탭바/feedTabBarIcon_unselected.imageset/feedTabBarIcon.svg
  SixthSense/Home/Resources/Assets.xcassets/탭바/mypageTabBarIcon_unselected.imageset/Contents.json
  SixthSense/Home/Resources/Assets.xcassets/탭바/mypageTabBarIcon_unselected.imageset/icon_mypage.svg
  SixthSense/Home/Sources/Feed/FeedBuilder.swift
  SixthSense/Home/Sources/Feed/FeedInteractor.swift
  SixthSense/Home/Sources/Feed/FeedRouter.swift
  SixthSense/Home/Sources/Feed/FeedViewController.swift
  SixthSense/Home/Sources/Home/HomeBuilder.swift
  SixthSense/Home/Sources/Home/HomeComponent.swift
  SixthSense/Home/Sources/Home/HomeRouter.swift
  SixthSense/Home/Sources/MyPage/Cell/MyPageHeaderItemCell.swift
  SixthSense/Home/Sources/MyPage/Cell/MyPageItemCell.swift
  SixthSense/Home/Sources/MyPage/DataSource/MyPageSection.swift
  SixthSense/Home/Sources/MyPage/RIB/MyPageBuilder.swift
  SixthSense/Home/Sources/MyPage/RIB/MyPageInteractor.swift
  SixthSense/Home/Sources/MyPage/RIB/MyPageRouter.swift
  SixthSense/Home/Sources/MyPage/RIB/MyPageViewController.swift
Labels: :sparkles: enhancement

#110 [App] 챌린지 등록 | 텍스트필드 UI를 구성했어요
  SixthSense/Challenge/Sources/Check/Views/CommentInputField.swift
  SixthSense/Challenge/Sources/Check/Views/TextFieldErrorView.swift
Labels: :sparkles: enhancement, :art: UI

#111 [App] `deploymentTarget`을 iOS 13 → 14로 올렸어요
  SixthSense/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: :sparkles: enhancement

#113 [App] 마이페이기 | 웹뷰와 로그아웃 팝업을 연결했어요.
  SixthSense/Home/Sources/ChallengeRegister/DataSource/ChallengeListSection.swift
  SixthSense/Home/Sources/ChallengeRegister/RIB/ChallengeRegisterViewController.swift
  SixthSense/Home/Sources/MyPage/Cell/MyPageHeaderItemCell.swift
  SixthSense/Home/Sources/MyPage/Cell/MyPageItemCell.swift
  SixthSense/Home/Sources/MyPage/DataSource/MyPageSection.swift
  SixthSense/Home/Sources/MyPage/DataSource/ViewModel/MyPageItemCellViewModel.swift
  SixthSense/Home/Sources/MyPage/RIB/MyPageBuilder.swift
  SixthSense/Home/Sources/MyPage/RIB/MyPageInteractor.swift
  SixthSense/Home/Sources/MyPage/RIB/MyPageRouter.swift
  SixthSense/Home/Sources/MyPage/RIB/MyPageViewController.swift
  SixthSense/Home/Sources/MyPageModify/RIB/MyPageModifyBuilder.swift
  SixthSense/Home/Sources/MyPageModify/RIB/MyPageModifyInteractor.swift
  SixthSense/Home/Sources/MyPageModify/RIB/MyPageModifyRouter.swift
  SixthSense/Home/Sources/MyPageModify/RIB/MyPageModifyViewController.swift
  SixthSense/Home/Sources/MyPageModify/View/UserInfoView.swift
  SixthSense/Home/Sources/MyPageWebView/RIB/MyPageWebViewBuilder.swift
  SixthSense/Home/Sources/MyPageWebView/RIB/MyPageWebViewInteractor.swift
  SixthSense/Home/Sources/MyPageWebView/RIB/MyPageWebViewRouter.swift
  SixthSense/Home/Sources/MyPageWebView/RIB/MyPageWebViewViewController.swift
Labels: :sparkles: enhancement

#115 [App] 챌린지 인증 | 보일러플레이트 코드를 추가하고 화면을 구성했어요
  SixthSense/Challenge/Sources/Detail/ChallengeDetailBuilder.swift
  SixthSense/Challenge/Sources/Detail/ChallengeDetailInteractor.swift
  SixthSense/Challenge/Sources/Detail/ChallengeDetailRouter.swift
  SixthSense/Challenge/Sources/Detail/ChallengeDetailViewController.swift
Labels: :sparkles: enhancement, :art: UI

#120 [App] 챌린지리스트 | 삭제 컨펌알럿과 삭제로직을 구현했어요
  SixthSense/Home/Sources/ChallengeList/ChallengeListInteractor.swift
  SixthSense/Home/Sources/ChallengeList/ChallengeListViewController.swift
  SixthSense/Home/Sources/ChallengeList/Domain/ChallengeListUseCase.swift
  SixthSense/Home/Sources/ChallengeList/Views/ChallengeItemCellViewModel.swift
Labels: :sparkles: enhancement, :art: UI

#122 [App] 인증확인 | 삭제버튼을 추가하고 삭제 인터렉션을 추가하였어요
  SixthSense/Challenge/Sources/Detail/ChallengeDetailBuilder.swift
  SixthSense/Challenge/Sources/Detail/ChallengeDetailInteractor.swift
  SixthSense/Challenge/Sources/Detail/ChallengeDetailUseCase.swift
  SixthSense/Challenge/Sources/Detail/ChallengeDetailViewController.swift
  SixthSense/Home/Sources/ChallengeList/ChallengeListInteractor.swift
  SixthSense/Home/Sources/ChallengeList/ChallengeListRouter.swift
Labels: :sparkles: enhancement, :art: UI

#123 [App] 인증추가 | 인증 추가 화면에서 사용하는 알럿을 추가하고 완료팝업을 구현했어요
  SixthSense/Challenge/Sources/Check/ChallengeCheckInteractor.swift
  SixthSense/Challenge/Sources/Check/ChallengeCheckUseCase.swift
  SixthSense/Challenge/Sources/Check/ChallengeCheckViewController.swift
  SixthSense/Challenge/Sources/Check/Views/ChallengeCheckCompletePopUp.swift
  SixthSense/DesignSystem/Resources/Assets.xcassets/브랜드/brand_icon.imageset/Contents.json
  SixthSense/DesignSystem/Resources/Assets.xcassets/브랜드/brand_icon.imageset/brand_icon.svg
Labels: :sparkles: enhancement, :art: UI

#124 [App] 인증완료 팝업에 폭죽 로티를 추가하고 내부 로직을 개선했어요
  SixthSense/Account/Project.swift
  SixthSense/Challenge/Project.swift
  SixthSense/Challenge/Sources/Check/ChallengeCheckViewController.swift
  SixthSense/Challenge/Sources/Check/Views/ChallengeCheckCompletePopUp.swift
  SixthSense/DesignSystem/Resources/Lotties/celebrate.json
  SixthSense/DesignSystem/Sources/Assets/LottieImages.swift
  SixthSense/Home/Sources/ChallengeList/ChallengeListInteractor.swift
  SixthSense/Home/Sources/ChallengeList/Domain/ChallengeListUseCase.swift
Labels: :sparkles: enhancement, :hammer: refactor, :art: UI

#128 [App] 마이너한 버그를 수정하고 코드를 정리했어요
  SixthSense/Account/Sources/SignUp/Presentation/SubViews/NicknameStepViewController.swift
  SixthSense/Account/Sources/User/Domain/Entities/User.swift
  SixthSense/Account/Sources/User/Domain/UseCases/UserUseCase.swift
  SixthSense/Account/Sources/User/Presentation/Cell/UserItemsSection.swift
  SixthSense/Account/Sources/User/Presentation/Cell/UserTableViewCell.swift
  SixthSense/Account/Sources/User/Presentation/UserInfoRIB/UserInfoBuilder.swift
  SixthSense/Account/Sources/User/Presentation/UserInfoRIB/UserInfoInteractor.swift
  SixthSense/Account/Sources/User/Presentation/UserInfoRIB/UserInfoRouter.swift
  SixthSense/Account/Sources/User/Presentation/UserInfoRIB/UserInfoViewController.swift
  SixthSense/Challenge/Sources/ChallengeRecommend/Presentation/RIB/ChallengeRecommendViewController.swift
  SixthSense/DesignSystem/Sources/Assets/AppFont.swift
  SixthSense/Home/Sources/ChallengeRegister/RIB/ChallengeRegisterInteractor.swift
  SixthSense/Home/Sources/ChallengeRegister/RIB/ChallengeRegisterViewController.swift
  SixthSense/Splash/Sources/SplashRIB/SplashBuilder.swift
  SixthSense/Splash/Sources/SplashRIB/SplashRouter.swift
Labels: :bug: bugfix, :eyes: dependent, :broom: chore

#127 [APP] 회원정보수정화면 Routing을 연결했어요
  SixthSense/Account/Sources/SignUp/Presentation/SubViews/NicknameStepViewController.swift
  SixthSense/Account/Sources/User/Domain/Entities/User.swift
  SixthSense/Account/Sources/User/Domain/UseCases/UserUseCase.swift
  SixthSense/Account/Sources/User/Presentation/Cell/UserItemsSection.swift
  SixthSense/Account/Sources/User/Presentation/Cell/UserTableViewCell.swift
  SixthSense/Account/Sources/User/Presentation/UserInfoRIB/UserInfoBuilder.swift
  SixthSense/Account/Sources/User/Presentation/UserInfoRIB/UserInfoInteractor.swift
  SixthSense/Account/Sources/User/Presentation/UserInfoRIB/UserInfoRouter.swift
  SixthSense/Account/Sources/User/Presentation/UserInfoRIB/UserInfoViewController.swift
  SixthSense/Challenge/Sources/ChallengeRecommend/Presentation/RIB/ChallengeRecommendViewController.swift
  SixthSense/DesignSystem/Sources/Assets/AppFont.swift
  SixthSense/Home/Sources/ChallengeRegister/RIB/ChallengeRegisterInteractor.swift
  SixthSense/Home/Sources/ChallengeRegister/RIB/ChallengeRegisterViewController.swift
  SixthSense/Home/Sources/MyPage/RIB/MyPageInteractor.swift
  SixthSense/Home/Sources/MyPage/RIB/MyPageRouter.swift
  SixthSense/Home/Sources/MyPageWebView/RIB/MyPageWebViewInteractor.swift
  SixthSense/Splash/Sources/SplashRIB/SplashBuilder.swift
  SixthSense/Splash/Sources/SplashRIB/SplashRouter.swift
Labels: :sparkles: enhancement, :eyes: dependent

#126 [App] 회원정보와 회원챌린지정보 API를 연결했어요
  SixthSense/Account/Sources/SignUp/Presentation/SubViews/NicknameStepViewController.swift
  SixthSense/Account/Sources/User/Domain/Entities/User.swift
  SixthSense/Account/Sources/User/Domain/UseCases/UserUseCase.swift
  SixthSense/Account/Sources/User/Presentation/Cell/UserItemsSection.swift
  SixthSense/Account/Sources/User/Presentation/Cell/UserTableViewCell.swift
  SixthSense/Account/Sources/User/Presentation/UserInfoRIB/UserInfoBuilder.swift
  SixthSense/Account/Sources/User/Presentation/UserInfoRIB/UserInfoInteractor.swift
  SixthSense/Account/Sources/User/Presentation/UserInfoRIB/UserInfoRouter.swift
  SixthSense/Account/Sources/User/Presentation/UserInfoRIB/UserInfoViewController.swift
  SixthSense/Challenge/Sources/ChallengeRecommend/Presentation/RIB/ChallengeRecommendViewController.swift
  SixthSense/DesignSystem/Sources/Assets/AppFont.swift
  SixthSense/Home/Sources/ChallengeRegister/RIB/ChallengeRegisterInteractor.swift
  SixthSense/Home/Sources/ChallengeRegister/RIB/ChallengeRegisterViewController.swift
  SixthSense/Home/Sources/Home/HomeBuilder.swift
  SixthSense/Home/Sources/Home/HomeComponent.swift
  SixthSense/Home/Sources/MyPage/Cell/MyPageHeaderItemCell.swift
  SixthSense/Home/Sources/MyPage/DataSource/MyPageSection.swift
  SixthSense/Home/Sources/MyPage/Domain/Entities/UserChallengeStatModel.swift
  SixthSense/Home/Sources/MyPage/Domain/Entities/UserInfoModel.swift
  SixthSense/Home/Sources/MyPage/Domain/Enums/GenderInfo.swift
  SixthSense/Home/Sources/MyPage/Domain/Enums/VeganStageInfo.swift
  SixthSense/Home/Sources/MyPage/Domain/MyPageHeaderViewModel.swift
  SixthSense/Home/Sources/MyPage/Domain/UseCases/MyPageUseCase.swift
  SixthSense/Home/Sources/MyPage/Domain/UserInfoPayload.swift
  SixthSense/Home/Sources/MyPage/RIB/MyPageBuilder.swift
  SixthSense/Home/Sources/MyPage/RIB/MyPageInteractor.swift
  SixthSense/Home/Sources/MyPage/RIB/MyPageRouter.swift
  SixthSense/Home/Sources/MyPage/RIB/MyPageViewController.swift
  SixthSense/Home/Sources/MyPageWebView/RIB/MyPageWebViewInteractor.swift
  SixthSense/Repository/Sources/User/UserAPI.swift
  SixthSense/Repository/Sources/User/UserRepository.swift
  SixthSense/Repository/Sources/User/UserRepositoryImpl.swift
  SixthSense/Splash/Sources/SplashRIB/SplashBuilder.swift
  SixthSense/Splash/Sources/SplashRIB/SplashRouter.swift
Labels: :sparkles: enhancement, :eyes: dependent

#125 [App] 회원정보수정 화면을 만들었어요
  SixthSense/Account/Sources/SignUp/Presentation/SubViews/NicknameStepViewController.swift
  SixthSense/Account/Sources/User/Domain/Entities/User.swift
  SixthSense/Account/Sources/User/Domain/UseCases/UserUseCase.swift
  SixthSense/Account/Sources/User/Presentation/Cell/UserItemsSection.swift
  SixthSense/Account/Sources/User/Presentation/Cell/UserTableViewCell.swift
  SixthSense/Account/Sources/User/Presentation/UserInfoRIB/UserInfoBuilder.swift
  SixthSense/Account/Sources/User/Presentation/UserInfoRIB/UserInfoInteractor.swift
  SixthSense/Account/Sources/User/Presentation/UserInfoRIB/UserInfoRouter.swift
  SixthSense/Account/Sources/User/Presentation/UserInfoRIB/UserInfoViewController.swift
  SixthSense/Challenge/Sources/ChallengeRecommend/Presentation/RIB/ChallengeRecommendViewController.swift
  SixthSense/DesignSystem/Sources/Assets/AppFont.swift
  SixthSense/Home/Sources/ChallengeRegister/RIB/ChallengeRegisterInteractor.swift
  SixthSense/Home/Sources/ChallengeRegister/RIB/ChallengeRegisterViewController.swift
  SixthSense/Home/Sources/Home/HomeBuilder.swift
  SixthSense/Home/Sources/Home/HomeComponent.swift
  SixthSense/Home/Sources/MyPage/Cell/MyPageHeaderItemCell.swift
  SixthSense/Home/Sources/MyPage/DataSource/MyPageSection.swift
  SixthSense/Home/Sources/MyPage/Domain/Entities/UserChallengeStatModel.swift
  SixthSense/Home/Sources/MyPage/Domain/Entities/UserInfoModel.swift
  SixthSense/Home/Sources/MyPage/Domain/Enums/GenderInfo.swift
  SixthSense/Home/Sources/MyPage/Domain/Enums/VeganStageInfo.swift
  SixthSense/Home/Sources/MyPage/Domain/MyPageHeaderViewModel.swift
  SixthSense/Home/Sources/MyPage/Domain/UseCases/MyPageUseCase.swift
  SixthSense/Home/Sources/MyPage/Domain/UserInfoPayload.swift
  SixthSense/Home/Sources/MyPage/RIB/MyPageBuilder.swift
  SixthSense/Home/Sources/MyPage/RIB/MyPageInteractor.swift
  SixthSense/Home/Sources/MyPage/RIB/MyPageRouter.swift
  SixthSense/Home/Sources/MyPage/RIB/MyPageViewController.swift
  SixthSense/Home/Sources/MyPageModify/RIB/MyPageModifyBuilder.swift
  SixthSense/Home/Sources/MyPageModify/RIB/MyPageModifyInteractor.swift
  SixthSense/Home/Sources/MyPageModify/RIB/MyPageModifyViewController.swift
  SixthSense/Home/Sources/MyPageModify/View/UserInfoView.swift
  SixthSense/Home/Sources/MyPageWebView/RIB/MyPageWebViewInteractor.swift
  SixthSense/Repository/Sources/User/UserAPI.swift
  SixthSense/Repository/Sources/User/UserRepository.swift
  SixthSense/Repository/Sources/User/UserRepositoryImpl.swift
  SixthSense/Splash/Sources/SplashRIB/SplashBuilder.swift
  SixthSense/Splash/Sources/SplashRIB/SplashRouter.swift
Labels: :sparkles: enhancement

#130 [Repository] 유저 챌린지 API를 구성했어요
  SixthSense/Home/Sources/Challenge/ChallengeBuilder.swift
  SixthSense/Home/Sources/ChallengeList/ChallengeListBuilder.swift
  SixthSense/Home/Sources/ChallengeList/ChallengeListInteractor.swift
  SixthSense/Home/Sources/ChallengeList/Domain/ChallengeListUseCase.swift
  SixthSense/Home/Sources/ChallengeList/Domain/UserChallengeList.swift
  SixthSense/Home/Sources/Home/HomeComponent.swift
  SixthSense/Repository/Sources/UserChallenge/UserChallengeAPI.swift
  SixthSense/Repository/Sources/UserChallenge/UserChallengeRepository.swift
  SixthSense/Repository/Sources/UserChallenge/UserChallengeRepositoryImpl.swift
Labels: :sparkles: enhancement

#132 [App] 인증확인 Payload를 구성하고 API를 붙혔어요
  SixthSense/Challenge/Sources/Detail/ChallengeDetailBuilder.swift
  SixthSense/Challenge/Sources/Detail/ChallengeDetailInteractor.swift
  SixthSense/Challenge/Sources/Detail/ChallengeDetailPayload.swift
  SixthSense/Challenge/Sources/Detail/ChallengeDetailUseCase.swift
  SixthSense/Challenge/Sources/Detail/ChallengeDetailViewController.swift
  SixthSense/Home/Sources/ChallengeList/ChallengeListInteractor.swift
  SixthSense/Home/Sources/ChallengeList/ChallengeListRouter.swift
  SixthSense/Home/Sources/ChallengeList/Domain/ChallengeListUseCase.swift
  SixthSense/Home/Sources/ChallengeList/Domain/UserChallengeList.swift
  SixthSense/Home/Sources/ChallengeList/Views/ChallengeItemCellViewModel.swift
Labels: :sparkles: enhancement, :eyes: dependent

#133 [App] 챌린지 리스트 fetch 로직을 개선하고 챌린지 추가 로직을 구현했어요
  SixthSense/Home/Sources/ChallengeList/ChallengeListBuilder.swift
  SixthSense/Home/Sources/ChallengeList/ChallengeListInteractor.swift
  SixthSense/Home/Sources/ChallengeList/ChallengeListViewController.swift
  SixthSense/Home/Sources/ChallengeList/Domain/ChallengeListUseCase.swift
  SixthSense/Home/Sources/ChallengeList/Views/ChallengeAddCell.swift
  SixthSense/Home/Sources/ChallengeList/Views/ChallengeEmptyView.swift
Labels: :sparkles: enhancement, :eyes: dependent, :art: UI

#134 [App] 홈 | 캘린더 ↔ 등록 간 기준일의 싱크를 맞추는 로직을 구성했어요
  SixthSense/Home/Sources/Challenge/ChallengeBuilder.swift
  SixthSense/Home/Sources/ChallengeCalendar/CalendarConfigure.swift
  SixthSense/Home/Sources/ChallengeRegister/RIB/ChallengeRegisterBuilder.swift
  SixthSense/Home/Sources/ChallengeRegister/RIB/ChallengeRegisterInteractor.swift
  SixthSense/Home/Sources/Home/HomeBuilder.swift
  SixthSense/Home/Sources/Home/HomeComponent.swift
Labels: :sparkles: enhancement, :eyes: dependent

#135 [App] 캘린더 fetch 로직을 구현하고 달성률에 따라 캘린더 아이콘을 구성하는 로직을 구현했어요
  SixthSense/Home/Sources/ChallengeCalendar/ChallengeCalendarBuilder.swift
  SixthSense/Home/Sources/ChallengeCalendar/ChallengeCalendarDayState.swift
  SixthSense/Home/Sources/ChallengeCalendar/ChallengeCalendarInteractor.swift
  SixthSense/Home/Sources/ChallengeCalendar/ChallengeCalendarUseCase.swift
  SixthSense/Home/Sources/ChallengeCalendar/ChallengeCalendarViewController+Calendar.swift
  SixthSense/Home/Sources/ChallengeCalendar/ChallengeCalendarViewController.swift
  SixthSense/Home/Sources/ChallengeCalendar/UserChallengeCalendarList.swift
  SixthSense/Home/Sources/ChallengeCalendar/Views/CalendarDayCell.swift
Labels: :sparkles: enhancement, :eyes: dependent

#136 [App] Root RIB UseCase 주입 로직을 개선하고 로그인 상태에 따라 첫화면을 다르게 보여주도록 구성했어요
  SixthSense/Account/Sources/SignIn/Presentation/SignInBuilder.swift
  SixthSense/Account/Sources/SignIn/Presentation/SignInInteractor.swift
  SixthSense/Account/Sources/SignUp/Presentation/SignUpBuilder.swift
  SixthSense/Account/Sources/SignUp/Presentation/SignUpInteractor.swift
  SixthSense/Splash/Sources/SplashRIB/SplashBuilder.swift
  SixthSense/Splash/Sources/SplashRIB/SplashRouter.swift
  SixthSense/VegannerApp/Sources/Root/RootRIB/RootBuilder.swift
  SixthSense/VegannerApp/Sources/Root/RootRIB/RootComponent.swift
  SixthSense/VegannerApp/Sources/Root/RootRIB/RootInteractor.swift
  SixthSense/VegannerApp/Sources/Root/RootRIB/RootUseCase.swift
Labels: :sparkles: enhancement, :eyes: dependent, :hammer: refactor

#138 [App] 로그아웃,회원탈퇴 API를 연결했어요
  SixthSense/Home/Sources/Home/HomeComponent.swift
  SixthSense/Home/Sources/MyPage/Domain/UseCases/MyPageUseCase.swift
  SixthSense/Home/Sources/MyPage/RIB/MyPageBuilder.swift
  SixthSense/Home/Sources/MyPage/RIB/MyPageInteractor.swift
  SixthSense/Home/Sources/MyPage/RIB/MyPageViewController.swift
  SixthSense/Home/Sources/MyPageModify/Domain/MyPageModifyUseCase.swift
  SixthSense/Home/Sources/MyPageModify/RIB/MyPageModifyBuilder.swift
  SixthSense/Home/Sources/MyPageModify/RIB/MyPageModifyInteractor.swift
  SixthSense/Repository/Sources/User/UserAPI.swift
  SixthSense/Repository/Sources/User/UserRepository.swift
  SixthSense/Repository/Sources/User/UserRepositoryImpl.swift
Labels: :sparkles: enhancement, :eyes: dependent, :hammer: refactor

#137 [App] 회원 정보 수정 화면들을 연결했어요
  SixthSense/Account/Sources/SignUp/Presentation/SignUpViewController.swift
  SixthSense/Account/Sources/SignUp/Presentation/SubViews/BirthStepViewController.swift
  SixthSense/Account/Sources/SignUp/Presentation/SubViews/GenderStepViewController.swift
  SixthSense/Account/Sources/SignUp/Presentation/SubViews/NicknameStepViewController.swift
  SixthSense/Account/Sources/SignUp/Presentation/SubViews/VeganStepViewController.swift
  SixthSense/Home/Project.swift
  SixthSense/Home/Sources/Home/HomeComponent.swift
  SixthSense/Home/Sources/MyPage/Domain/UseCases/MyPageUseCase.swift
  SixthSense/Home/Sources/MyPage/RIB/MyPageBuilder.swift
  SixthSense/Home/Sources/MyPage/RIB/MyPageInteractor.swift
  SixthSense/Home/Sources/MyPage/RIB/MyPageViewController.swift
  SixthSense/Home/Sources/MyPageModify/Domain/MyPageModifyUseCase.swift
  SixthSense/Home/Sources/MyPageModify/RIB/MyPageModifyBuilder.swift
  SixthSense/Home/Sources/MyPageModify/RIB/MyPageModifyInteractor.swift
  SixthSense/Home/Sources/MyPageModify/RIB/MyPageModifyRouter.swift
  SixthSense/Home/Sources/MyPageModify/RIB/MyPageModifyViewController.swift
  SixthSense/Home/Sources/MyPageModify/View/UserInfoView.swift
  SixthSense/Home/Sources/MyPageModifyInfo/ModifyInfo.swift
  SixthSense/Home/Sources/MyPageModifyInfo/RIB/MyPageModifyInfoBuilder.swift
  SixthSense/Home/Sources/MyPageModifyInfo/RIB/MyPageModifyInfoInteractor.swift
  SixthSense/Home/Sources/MyPageModifyInfo/RIB/MyPageModifyInfoRouter.swift
  SixthSense/Home/Sources/MyPageModifyInfo/RIB/MyPageModifyInfoViewController.swift
  SixthSense/Repository/Sources/User/UserAPI.swift
  SixthSense/Repository/Sources/User/UserRepository.swift
  SixthSense/Repository/Sources/User/UserRepositoryImpl.swift
Labels: :sparkles: enhancement

#140 [App] 로그아웃, 회원탈퇴 라우팅 및 로직을 적용했어요
  SixthSense/Challenge/Sources/ChallengeRecommend/Presentation/RIB/ChallengeRecommendBuilder.swift
  SixthSense/Home/Sources/ChallengeCalendar/ChallengeCalendarViewController.swift
  SixthSense/Home/Sources/ChallengeRegister/Cell/ChallengeListItemCell.swift
  SixthSense/Home/Sources/ChallengeRegister/RIB/ChallengeRegisterBuilder.swift
  SixthSense/Home/Sources/ChallengeRegister/RIB/ChallengeRegisterInteractor.swift
  SixthSense/Home/Sources/ChallengeRegister/RIB/ChallengeRegisterViewController.swift
  SixthSense/Home/Sources/Home/HomeInteractor.swift
  SixthSense/Home/Sources/Home/HomeRouter.swift
  SixthSense/Home/Sources/Home/RootTabBarController.swift
  SixthSense/Home/Sources/MyPage/Domain/UseCases/MyPageUseCase.swift
  SixthSense/Home/Sources/MyPage/RIB/MyPageBuilder.swift
  SixthSense/Home/Sources/MyPage/RIB/MyPageInteractor.swift
  SixthSense/Home/Sources/MyPage/RIB/MyPageViewController.swift
  SixthSense/Home/Sources/MyPageModify/RIB/MyPageModifyInteractor.swift
  SixthSense/Splash/Sources/SplashRIB/SplashRouter.swift
  SixthSense/VegannerApp/Sources/Root/RootRIB/RootInteractor.swift
Labels: :sparkles: enhancement, :hammer: refactor

#143 [App] SignUpComplete RIB을 구성했어요
  SixthSense/Account/Sources/SignIn/Presentation/SignInInteractor.swift
  SixthSense/Account/Sources/SignIn/Presentation/SignInRouter.swift
  SixthSense/Account/Sources/SignIn/Presentation/SignInViewController.swift
  SixthSense/Account/Sources/SignUp/Presentation/SignUpBuilder.swift
  SixthSense/Account/Sources/SignUp/Presentation/SignUpInteractor.swift
  SixthSense/Account/Sources/SignUp/Presentation/SignUpRouter.swift
  SixthSense/Account/Sources/SignUpComplete/SignUpCompleteBuilder.swift
  SixthSense/Account/Sources/SignUpComplete/SignUpCompleteInteractor.swift
  SixthSense/Account/Sources/SignUpComplete/SignUpCompleteRouter.swift
  SixthSense/Account/Sources/SignUpComplete/SignUpCompleteViewController.swift
Labels: :sparkles: enhancement, :eyes: dependent

#141 [App] 회원정보 수정 API를 연결했어요
  SixthSense/Account/Sources/SignIn/Presentation/SignInInteractor.swift
  SixthSense/Account/Sources/SignIn/Presentation/SignInRouter.swift
  SixthSense/Account/Sources/SignIn/Presentation/SignInViewController.swift
  SixthSense/Account/Sources/SignUp/Presentation/Enums/Gender.swift
  SixthSense/Account/Sources/SignUp/Presentation/Enums/VeganStage.swift
  SixthSense/Account/Sources/SignUp/Presentation/SignUpBuilder.swift
  SixthSense/Account/Sources/SignUp/Presentation/SignUpInteractor.swift
  SixthSense/Account/Sources/SignUp/Presentation/SignUpRouter.swift
  SixthSense/Account/Sources/SignUp/Presentation/SubViews/BirthStepViewController.swift
  SixthSense/Account/Sources/SignUp/Presentation/SubViews/GenderStepViewController.swift
  SixthSense/Account/Sources/SignUp/Presentation/SubViews/NicknameStepViewController.swift
  SixthSense/Account/Sources/SignUp/Presentation/SubViews/VeganStepViewController.swift
  SixthSense/Account/Sources/SignUpComplete/SignUpCompleteBuilder.swift
  SixthSense/Account/Sources/SignUpComplete/SignUpCompleteInteractor.swift
  SixthSense/Account/Sources/SignUpComplete/SignUpCompleteRouter.swift
  SixthSense/Account/Sources/SignUpComplete/SignUpCompleteViewController.swift
  SixthSense/Home/Sources/MyPage/Domain/Enums/GenderInfo.swift
  SixthSense/Home/Sources/MyPage/Domain/Enums/VeganStageInfo.swift
  SixthSense/Home/Sources/MyPage/Domain/UserInfoPayload.swift
  SixthSense/Home/Sources/MyPageModify/RIB/MyPageModifyBuilder.swift
  SixthSense/Home/Sources/MyPageModify/RIB/MyPageModifyInteractor.swift
  SixthSense/Home/Sources/MyPageModify/RIB/MyPageModifyRouter.swift
  SixthSense/Home/Sources/MyPageModifyInfo/Domain/MyPageModifyInfoUseCase.swift
  SixthSense/Home/Sources/MyPageModifyInfo/RIB/MyPageModifyInfoBuilder.swift
  SixthSense/Home/Sources/MyPageModifyInfo/RIB/MyPageModifyInfoInteractor.swift
  SixthSense/Home/Sources/MyPageModifyInfo/RIB/MyPageModifyInfoViewController.swift
  SixthSense/Repository/Sources/AccessTokenService/AccessToken.swift
  SixthSense/Repository/Sources/AccessTokenService/AccessTokenServiceImpl.swift
  SixthSense/Repository/Sources/User/Requests/UserInfoRequest.swift
  SixthSense/Repository/Sources/User/UserAPI.swift
  SixthSense/Repository/Sources/User/UserRepository.swift
  SixthSense/Repository/Sources/User/UserRepositoryImpl.swift
Labels: :sparkles: enhancement, :hammer: refactor

#144 [Core] 앱 업로드에서 발생한 문제를 해결하고 앱 아이콘을 추가했어요
  .gitignore
  SixthSense/Challenge/Project.swift
  SixthSense/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  SixthSense/VegannerApp/Resources/Assets.xcassets/AppIcon.appiconset/100.png
  SixthSense/VegannerApp/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  SixthSense/VegannerApp/Resources/Assets.xcassets/AppIcon.appiconset/114.png
  SixthSense/VegannerApp/Resources/Assets.xcassets/AppIcon.appiconset/120.png
  SixthSense/VegannerApp/Resources/Assets.xcassets/AppIcon.appiconset/128.png
  SixthSense/VegannerApp/Resources/Assets.xcassets/AppIcon.appiconset/144.png
  SixthSense/VegannerApp/Resources/Assets.xcassets/AppIcon.appiconset/152.png
  SixthSense/VegannerApp/Resources/Assets.xcassets/AppIcon.appiconset/16.png
  SixthSense/VegannerApp/Resources/Assets.xcassets/AppIcon.appiconset/167.png
  SixthSense/VegannerApp/Resources/Assets.xcassets/AppIcon.appiconset/172.png
  SixthSense/VegannerApp/Resources/Assets.xcassets/AppIcon.appiconset/180.png
  SixthSense/VegannerApp/Resources/Assets.xcassets/AppIcon.appiconset/196.png
  SixthSense/VegannerApp/Resources/Assets.xcassets/AppIcon.appiconset/20.png
  SixthSense/VegannerApp/Resources/Assets.xcassets/AppIcon.appiconset/216.png
  SixthSense/VegannerApp/Resources/Assets.xcassets/AppIcon.appiconset/256.png
  SixthSense/VegannerApp/Resources/Assets.xcassets/AppIcon.appiconset/29.png
  SixthSense/VegannerApp/Resources/Assets.xcassets/AppIcon.appiconset/32.png
  SixthSense/VegannerApp/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  SixthSense/VegannerApp/Resources/Assets.xcassets/AppIcon.appiconset/48.png
  SixthSense/VegannerApp/Resources/Assets.xcassets/AppIcon.appiconset/50.png
  SixthSense/VegannerApp/Resources/Assets.xcassets/AppIcon.appiconset/512.png
  SixthSense/VegannerApp/Resources/Assets.xcassets/AppIcon.appiconset/55.png
  SixthSense/VegannerApp/Resources/Assets.xcassets/AppIcon.appiconset/57.png
  SixthSense/VegannerApp/Resources/Assets.xcassets/AppIcon.appiconset/58.png
  SixthSense/VegannerApp/Resources/Assets.xcassets/AppIcon.appiconset/60.png
  SixthSense/VegannerApp/Resources/Assets.xcassets/AppIcon.appiconset/64.png
  SixthSense/VegannerApp/Resources/Assets.xcassets/AppIcon.appiconset/72.png
  SixthSense/VegannerApp/Resources/Assets.xcassets/AppIcon.appiconset/76.png
  SixthSense/VegannerApp/Resources/Assets.xcassets/AppIcon.appiconset/80.png
  SixthSense/VegannerApp/Resources/Assets.xcassets/AppIcon.appiconset/87.png
  SixthSense/VegannerApp/Resources/Assets.xcassets/AppIcon.appiconset/88.png
  SixthSense/VegannerApp/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: :bug: bugfix, :art: UI

#147 [App] 홈 | 캘린더와 리스트에 있는 버그를 수정했어요
  SixthSense/Home/Sources/Challenge/ChallengeBuilder.swift
  SixthSense/Home/Sources/ChallengeCalendar/CalendarConfigure.swift
  SixthSense/Home/Sources/ChallengeCalendar/ChallengeCalendarBuilder.swift
  SixthSense/Home/Sources/ChallengeCalendar/ChallengeCalendarDayState.swift
  SixthSense/Home/Sources/ChallengeCalendar/ChallengeCalendarInteractor.swift
  SixthSense/Home/Sources/ChallengeList/ChallengeListBuilder.swift
  SixthSense/Home/Sources/ChallengeList/ChallengeListInteractor.swift
  SixthSense/Home/Sources/ChallengeList/Domain/ChallengeListUseCase.swift
  SixthSense/Repository/Sources/UserChallenge/UserChallengeAPI.swift
Labels: :bug: bugfix, :art: UI

#148 [App] 챌린지 등록 | UI 버그 수정과 요구사항을 추가했어요
  SixthSense/Challenge/Sources/ChallengeRecommend/Presentation/RIB/ChallengeRecommendInteractor.swift
  SixthSense/Home/Sources/ChallengeCalendar/CalendarConfigure.swift
  SixthSense/Home/Sources/ChallengeRegister/Cell/CategoryTabItemCell.swift
  SixthSense/Home/Sources/ChallengeRegister/Cell/ChallengeListItemCell.swift
  SixthSense/Home/Sources/ChallengeRegister/RIB/ChallengeRegisterInteractor.swift
  SixthSense/Home/Sources/ChallengeRegister/RIB/ChallengeRegisterViewController.swift
Labels: :bug: bugfix, :sparkles: enhancement, :eyes: dependent, :hammer: refactor

#150 [App] 회원정보수정 API 응답을 토스트로 반영했어요
  SixthSense/Home/Sources/MyPage/RIB/MyPageBuilder.swift
  SixthSense/Home/Sources/MyPage/RIB/MyPageInteractor.swift
  SixthSense/Home/Sources/MyPage/RIB/MyPageRouter.swift
  SixthSense/Home/Sources/MyPageModify/RIB/MyPageModifyBuilder.swift
  SixthSense/Home/Sources/MyPageModify/RIB/MyPageModifyInteractor.swift
  SixthSense/Home/Sources/MyPageModify/RIB/MyPageModifyRouter.swift
  SixthSense/Home/Sources/MyPageModify/RIB/MyPageModifyViewController.swift
  SixthSense/Home/Sources/MyPageModifyInfo/Domain/MyPageModifyInfoUseCase.swift
  SixthSense/Home/Sources/MyPageModifyInfo/RIB/MyPageModifyInfoBuilder.swift
  SixthSense/Home/Sources/MyPageModifyInfo/RIB/MyPageModifyInfoInteractor.swift
  SixthSense/Home/Sources/MyPageModifyInfo/RIB/MyPageModifyInfoViewController.swift
  SixthSense/Repository/Sources/User/UserRepositoryImpl.swift
Labels: :sparkles: enhancement

#151 [App] 홈, 온보딩, 챌린지에서 발생한 버그를 수정했어요
  SixthSense/Account/Sources/Extensions/UILabel+.swift
  SixthSense/Account/Sources/SignIn/Presentation/SignInViewController.swift
  SixthSense/Challenge/Sources/Check/ChallengeCheckViewController.swift
  SixthSense/Challenge/Sources/Check/Views/ChallengeCheckCompletePopUp.swift
  SixthSense/Challenge/Sources/Detail/ChallengeDetailViewController.swift
  SixthSense/DesignSystem/Resources/Lotties/temp_logo.json
  SixthSense/DesignSystem/Sources/Assets/LottieImages.swift
  SixthSense/Home/Sources/Challenge/ChallengeBuilder.swift
  SixthSense/Home/Sources/ChallengeList/ChallengeListBuilder.swift
  SixthSense/Home/Sources/ChallengeList/ChallengeListInteractor.swift
  SixthSense/Home/Sources/ChallengeList/ChallengeListViewController.swift
  SixthSense/Home/Sources/ChallengeList/Domain/ChallengeListUseCase.swift
  SixthSense/Home/Sources/ChallengeList/Views/ChallengeEmptyView.swift
  SixthSense/Repository/Sources/Network/NetworkImpl.swift
  SixthSense/Tuist/Dependencies.swift
Labels: :bug: bugfix, :art: UI

#153 [App] 홈 | 이미지 리소스를 변경하고, 토큰 이슈를 해결했어요
  SixthSense/DesignSystem/Resources/Assets.xcassets/check.imageset/Contents.json
  SixthSense/DesignSystem/Resources/Assets.xcassets/check.imageset/check.svg
  SixthSense/DesignSystem/Resources/Assets.xcassets/chevronDown.imageset/chevronDown.svg
  SixthSense/Home/Resources/Assets.xcassets/챌린지리스트/challenge_empty.imageset/challenge_empty.svg
  SixthSense/Home/Resources/Assets.xcassets/탭바/homeTabBarIcon.imageset/homeTabBarIcon.svg
  SixthSense/Home/Sources/ChallengeCalendar/ChallengeCalendarViewController+Calendar.swift
  SixthSense/Home/Sources/ChallengeCalendar/Views/CalendarDayCell.swift
  SixthSense/Home/Sources/ChallengeList/ChallengeListInteractor.swift
  SixthSense/Home/Sources/ChallengeList/Views/ChallengeWaitingItemCell.swift
  SixthSense/Home/Sources/Home/Views/HomeTabBarItem.swift
  SixthSense/Home/Sources/MyPage/Domain/UseCases/MyPageUseCase.swift
  SixthSense/Home/Sources/MyPage/RIB/MyPageBuilder.swift
  SixthSense/Home/Sources/MyPageModify/Domain/MyPageModifyUseCase.swift
  SixthSense/Home/Sources/MyPageModify/RIB/MyPageModifyBuilder.swift
  SixthSense/Home/Sources/MyPageModify/View/UserInfoView.swift
  SixthSense/Home/Sources/MyPageWebView/RIB/MyPageWebViewViewController.swift
Labels: :bug: bugfix, :sparkles: enhancement, :art: UI

#156 [App] 프로덕션 앱 설정에서 발생한 오류를 해결하고 스플래시 로티 애니메이션을 추가했어요
  SixthSense/Home/Sources/ChallengeCalendar/Views/CalendarDayCell.swift
  SixthSense/Splash/Sources/SplashRIB/SplashViewController.swift
  SixthSense/Utils/Sources/Logger/PrintLogger.swift
  SixthSense/VegannerApp/Sources/App/AppDelegate+Debug.swift
  SixthSense/VegannerApp/VegannerApp.entitlements
Labels: :bug: bugfix, :art: UI

#157 [App] 비회원 화면을 추가했어요
  SixthSense/Challenge/Sources/ChallengeRecommend/Presentation/RIB/ChallengeRecommendInteractor.swift
  SixthSense/Challenge/Sources/ChallengeRecommend/Presentation/RIB/ChallengeRecommendViewController.swift
  SixthSense/Home/Sources/ChallengeRegister/Domain/UseCases/ChallengeRegisterUseCase.swift
  SixthSense/Home/Sources/ChallengeRegister/RIB/ChallengeRegisterBuilder.swift
  SixthSense/Home/Sources/ChallengeRegister/RIB/ChallengeRegisterInteractor.swift
  SixthSense/Home/Sources/ChallengeRegister/RIB/ChallengeRegisterViewController.swift
  SixthSense/Home/Sources/Home/HomeComponent.swift
  SixthSense/Home/Sources/MyPage/Cell/MyPageHeaderItemCell.swift
  SixthSense/Home/Sources/MyPage/DataSource/MyPageSection.swift
  SixthSense/Home/Sources/MyPage/Domain/MyPageHeaderViewModel.swift
  SixthSense/Home/Sources/MyPage/Domain/UseCases/MyPageUseCase.swift
  SixthSense/Home/Sources/MyPage/RIB/MyPageInteractor.swift
  SixthSense/Home/Sources/MyPage/RIB/MyPageViewController.swift
Labels: :bug: bugfix, :sparkles: enhancement, :art: UI

#158 [BUGFIX] 작은 화면 대응 - cell 크기를 조절했어요
  SixthSense/Challenge/Sources/ChallengeRecommend/Presentation/Cell/RecommendItemCell.swift
  SixthSense/Challenge/Sources/ChallengeRecommend/Presentation/RIB/ChallengeRecommendViewController.swift
Labels: :bug: bugfix
