Repository TheSixthSense/app-ios, pull requests merged in 2022-07, with the labels that each got.

#7 [Core] 앱 내 데이터를 저장하기 위한 `LocalPersistence` 로직을 작성하였어요
  SixthSense/SixthSense/Sources/App/Persistence/LocalPersistence.swift
  SixthSense/SixthSense/Sources/App/Persistence/LocalPersistenceImpl.swift
Labels: enhancement

#9 [Core] `User` Entity를 만들었어요.
  SixthSense/SixthSense/Sources/User/Domain/Entities/User.swift
Labels: enhancement

#12 [Utils] Logger에 대한 스펙을 정의하고 `SwiftyBeaver` Logger를 추가하였어요
  .gitignore
  SixthSense/Configs/base.xcconfig
  SixthSense/Configs/debug.xcconfig
  SixthSense/Configs/release.xcconfig
  SixthSense/Configs/version.xcconfig
  SixthSense/SixthSense/Sources/App/AppDelegate+Debug.swift
  SixthSense/SixthSense/Sources/App/Configuration.swift
  SixthSense/SixthSense/Sources/App/Logger/Loggable.swift
  SixthSense/SixthSense/Sources/App/Logger/PrintLogger.swift
  SixthSense/SixthSense/Sources/App/Logger/SwiftyBeaverLogger.swift
  SixthSense/SixthSense/Supporting Files/Info.plist
Labels: enhancement

#17 [iOS] `RootRIB`을 추가했어요
  .gitignore
  SixthSense/SixthSense/Sources/App/AppComponent.swift
  SixthSense/SixthSense/Sources/App/AppDelegate.swift
  SixthSense/SixthSense/Sources/App/ViewController.swift
  SixthSense/SixthSense/Sources/Root/Navigation/NavigateViewControllable.swift
  SixthSense/SixthSense/Sources/Root/RootRIB/RootBuilder.swift
  SixthSense/SixthSense/Sources/Root/RootRIB/RootComponent+UserInfo.swift
  SixthSense/SixthSense/Sources/Root/RootRIB/RootInteractor.swift
  SixthSense/SixthSense/Sources/Root/RootRIB/RootRouter.swift
  SixthSense/SixthSense/Sources/Root/RootRIB/RootViewController.swift
  SixthSense/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: enhancement

#18 [Repository] `UserRepository` 스펙을 정의하고 구현하였어요
  SixthSense/SixthSense/Sources/App/Repository/UserAPI.swift
  SixthSense/SixthSense/Sources/App/Repository/UserRepository.swift
  SixthSense/SixthSense/Sources/App/Repository/UserRepositoryImpl.swift
Labels: enhancement

#19 [iOS] UserInfoRIB을 만들었어요
  SixthSense/SixthSense/Sources/Common/ClassNameProtocol.swift
  SixthSense/SixthSense/Sources/Root/RootRIB/RootBuilder.swift
  SixthSense/SixthSense/Sources/Root/RootRIB/RootComponent+UserInfo.swift
  SixthSense/SixthSense/Sources/Root/RootRIB/RootRouter.swift
  SixthSense/SixthSense/Sources/User/Presentation/Cell/UserItemsSection.swift
  SixthSense/SixthSense/Sources/User/Presentation/Cell/UserTableViewCell.swift
  SixthSense/SixthSense/Sources/User/Presentation/UserInfoRIB/UserInfoBuilder.swift
  SixthSense/SixthSense/Sources/User/Presentation/UserInfoRIB/UserInfoInteractor.swift
  SixthSense/SixthSense/Sources/User/Presentation/UserInfoRIB/UserInfoRouter.swift
  SixthSense/SixthSense/Sources/User/Presentation/UserInfoRIB/UserInfoViewController.swift
Labels: enhancement

#21 [iOS] UserUseCase를 구현했어요
  SixthSense/SixthSense/Sources/App/AppComponent.swift
  SixthSense/SixthSense/Sources/Common/Extensions/UI/UIStackView+.swift
  SixthSense/SixthSense/Sources/Common/Extensions/UI/UIView+.swift
  SixthSense/SixthSense/Sources/Root/RootRIB/RootBuilder.swift
  SixthSense/SixthSense/Sources/Root/RootRIB/RootComponent+UserInfo.swift
  SixthSense/SixthSense/Sources/User/Domain/Entities/User.swift
  SixthSense/SixthSense/Sources/User/Domain/UseCases/UserUseCase.swift
  SixthSense/SixthSense/Sources/User/Presentation/Cell/UserItemsSection.swift
  SixthSense/SixthSense/Sources/User/Presentation/Cell/UserTableViewCell.swift
  SixthSense/SixthSense/Sources/User/Presentation/UserInfoRIB/UserInfoBuilder.swift
  SixthSense/SixthSense/Sources/User/Presentation/UserInfoRIB/UserInfoInteractor.swift
  SixthSense/SixthSense/Sources/User/Presentation/UserInfoRIB/UserInfoViewController.swift
Labels: enhancement, dependent

#23 Dev 타겟만 번들 ID에 `dev`를 추가했어요
  SixthSense/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: chore

#26 [Github] Issue, PR template을 추가했어요
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/todo_issue.md
  .github/pull_request_template.md
Labels: :broom: chore

#25 [Infra] Matchfile을 수정하였어요
  SixthSense/fastlane/Matchfile
Labels: :robot: CI/CD

#32 [Chore] 깃허브 issue template을 수정해요
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/todo-issue.md
Labels: :broom: chore

#36 [계정] `Account` 모듈을 추가하고 연습예제인 `UserRIB`을 모듈내로 고립시켰어요
  SixthSense/Account/Project.swift
  SixthSense/Account/Sources/Extensions/ClassNameProtocol.swift
  SixthSense/Account/Sources/Extensions/UI/UIStackView+.swift
  SixthSense/Account/Sources/Extensions/UI/UIView+.swift
  SixthSense/Account/Sources/User/Domain/Entities/User.swift
  SixthSense/Account/Sources/User/Domain/UseCases/UserUseCase.swift
  SixthSense/Account/Sources/User/Presentation/Cell/UserItemsSection.swift
  SixthSense/Account/Sources/User/Presentation/Cell/UserTableViewCell.swift
  SixthSense/Account/Sources/User/Presentation/UserInfoRIB/UserInfoBuilder.swift
  SixthSense/Account/Sources/User/Presentation/UserInfoRIB/UserInfoInteractor.swift
  SixthSense/Account/Sources/User/Presentation/UserInfoRIB/UserInfoRouter.swift
  SixthSense/Account/Sources/User/Presentation/UserInfoRIB/UserInfoViewController.swift
  SixthSense/Repository/Project.swift
  SixthSense/Storage/Project.swift
  SixthSense/Tuist/ProjectDescriptionHelpers/ProjectName.swift
  SixthSense/Utils/Project.swift
  SixthSense/VegannerApp/Project.swift
  SixthSense/VegannerApp/Sources/Root/RootRIB/RootBuilder.swift
  SixthSense/VegannerApp/Sources/Root/RootRIB/RootComponent+UserInfo.swift
  SixthSense/VegannerApp/Sources/Root/RootRIB/RootInteractor.swift
  SixthSense/VegannerApp/Sources/Root/RootRIB/RootRouter.swift
  SixthSense/VegannerApp/Sources/Root/RootRIB/RootViewController.swift
  SixthSense/Workspace.swift
Labels: :sparkles: enhancement

#38 [UI] DesignSystem 모듈을 만들어요
  .gitignore
  SixthSense/DesignSystem/Project.swift
  SixthSense/DesignSystem/Resources/Pretendard-Bold.otf
  SixthSense/DesignSystem/Resources/Pretendard-Regular.otf
  SixthSense/DesignSystem/Resources/TmoneyRoundWindExtraBold.otf
  SixthSense/DesignSystem/Resources/TmoneyRoundWindRegular.otf
  SixthSense/DesignSystem/Sources/AppTextField.swift
  SixthSense/DesignSystem/Sources/Assets/AppColor.swift
  SixthSense/DesignSystem/Sources/Assets/AppFont.swift
  SixthSense/DesignSystem/Sources/Buttons/AppButton.swift
  SixthSense/DesignSystem/Sources/Buttons/ButtonProtocol.swift
  SixthSense/DesignSystem/Sources/Buttons/SelectButton.swift
  SixthSense/Makefile
  SixthSense/Tuist/Dependencies.swift
  SixthSense/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  SixthSense/Tuist/ProjectDescriptionHelpers/ProjectName.swift
  SixthSense/VegannerApp/Project.swift
Labels: :sparkles: enhancement, :art: UI

#41 [Splash] 스플래시 모듈을 작성하고 스플래시를 구성했어요
  .gitignore
  SixthSense/Account/Sources/User/Presentation/UserInfoRIB/UserInfoBuilder.swift
  SixthSense/Account/Sources/User/Presentation/UserInfoRIB/UserInfoInteractor.swift
  SixthSense/Account/Sources/User/Presentation/UserInfoRIB/UserInfoViewController.swift
  SixthSense/DesignSystem/Project.swift
  SixthSense/Splash/Project.swift
  SixthSense/Splash/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  SixthSense/Splash/Resources/Assets.xcassets/Contents.json
  SixthSense/Splash/Resources/temp_logo.json
  SixthSense/Splash/Sources/SplashRIB/SplashBuilder.swift
  SixthSense/Splash/Sources/SplashRIB/SplashInteractor.swift
  SixthSense/Splash/Sources/SplashRIB/SplashRouter.swift
  SixthSense/Splash/Sources/SplashRIB/SplashViewController.swift
  SixthSense/Splash/Sources/Utils/ViewControllable+Utils.swift
  SixthSense/Tuist/Dependencies.swift
  SixthSense/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  SixthSense/Tuist/ProjectDescriptionHelpers/ProjectName.swift
  SixthSense/Tuist/ProjectDescriptionHelpers/ResourcesExtension.swift
  SixthSense/VegannerApp/Project.swift
  SixthSense/VegannerApp/Resources/Base.lproj/Main.storyboard
  SixthSense/VegannerApp/Sources/Root/Navigation/ViewControllable+Utils.swift
  SixthSense/VegannerApp/Sources/Root/RootRIB/RootBuilder.swift
  SixthSense/VegannerApp/Sources/Root/RootRIB/RootComponent+Splash.swift
  SixthSense/VegannerApp/Sources/Root/RootRIB/RootInteractor.swift
  SixthSense/VegannerApp/Sources/Root/RootRIB/RootRouter.swift
  SixthSense/VegannerApp/Sources/Root/RootRIB/RootViewController.swift
Labels: :sparkles: enhancement

#43 [Account] `SignIn`RIB을 구성하고 애플 로그인 기능을 구현했어요
  SixthSense/Account/Project.swift
  SixthSense/Account/Sources/Extensions/ASAuthorizationControllerProxy.swift
  SixthSense/Account/Sources/Extensions/AuthenticationService+Rx.swift
  SixthSense/Account/Sources/SignIn/Domain/SignInUseCase.swift
  SixthSense/Account/Sources/SignIn/Presentation/SignInBuilder.swift
  SixthSense/Account/Sources/SignIn/Presentation/SignInInteractor.swift
  SixthSense/Account/Sources/SignIn/Presentation/SignInRouter.swift
  SixthSense/Account/Sources/SignIn/Presentation/SignInViewController.swift
  SixthSense/DesignSystem/Project.swift
  SixthSense/DesignSystem/Resources/Lotties/temp_logo.json
  SixthSense/DesignSystem/Sources/Assets/LottieImages.swift
  SixthSense/Splash/Sources/SplashRIB/SplashBuilder.swift
  SixthSense/Splash/Sources/SplashRIB/SplashInteractor.swift
  SixthSense/Splash/Sources/SplashRIB/SplashRouter.swift
  SixthSense/Splash/Sources/SplashRIB/SplashViewController.swift
  SixthSense/Splash/Sources/Utils/ViewControllable+Utils.swift
  SixthSense/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  SixthSense/VegannerApp/Sources/Root/RootRIB/RootRouter.swift
  SixthSense/VegannerApp/VegannerAppDev.entitlements
Labels: :sparkles: enhancement

#44 [UI] 디자인 컴포넌트 수정
  SixthSense/DesignSystem/Sources/AppLabel.swift
  SixthSense/DesignSystem/Sources/AppTextField.swift
  SixthSense/DesignSystem/Sources/Buttons/AppButton.swift
  SixthSense/DesignSystem/Sources/Buttons/SelectButton.swift
Labels: :art: UI

#46 Feature/#45
  .gitignore
  SixthSense/Account/Project.swift
  SixthSense/Account/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  SixthSense/Account/Resources/Assets.xcassets/Contents.json
  SixthSense/Account/Resources/Assets.xcassets/onboard_title.imageset/Contents.json
  SixthSense/Account/Resources/Assets.xcassets/onboard_title.imageset/onboard_title.svg
  SixthSense/Account/Sources/SignIn/Presentation/SignInViewController.swift
  SixthSense/DesignSystem/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  SixthSense/DesignSystem/Resources/Assets.xcassets/Contents.json
  SixthSense/DesignSystem/Resources/Assets.xcassets/bi_title.imageset/Contents.json
  SixthSense/DesignSystem/Resources/Assets.xcassets/bi_title.imageset/bi_title.svg
  SixthSense/DesignSystem/Sources/Assets/AppColor.swift
  SixthSense/Splash/Resources/Assets.xcassets/splash_logo.imageset/Contents.json
  SixthSense/Splash/Resources/Assets.xcassets/splash_logo.imageset/splash_logo.svg
  SixthSense/Splash/Resources/Assets.xcassets/splash_title.imageset/Contents.json
  SixthSense/Splash/Resources/Assets.xcassets/splash_title.imageset/splash_title.svg
  SixthSense/Splash/Resources/temp_logo.json
  SixthSense/Splash/Sources/Extensions/UIStackView.swift
  SixthSense/Splash/Sources/Extensions/UIView+.swift
  SixthSense/Splash/Sources/SplashRIB/SplashViewController.swift
  SixthSense/VegannerApp/Resources/Base.lproj/LaunchScreen.storyboard
Labels: :sparkles: enhancement, :art: UI

#50 [Repository] `baseURL`을 추가하고 에러처리를 로직을 적용했어요
  SixthSense/Repository/Sources/Base/BaseAPI.swift
  SixthSense/Repository/Sources/Base/EndPoint.swift
  SixthSense/Repository/Sources/Extensions/Dictionary+.swift
  SixthSense/Repository/Sources/Network/APIError.swift
  SixthSense/Repository/Sources/Network/ErrorResponse.swift
  SixthSense/Repository/Sources/Network/NetworkImpl.swift
  SixthSense/Supporting Files/Info.plist
  SixthSense/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  SixthSense/Utils/Sources/Logger/Configuration.swift
  SixthSense/VegannerApp/Supporting Files/Info.plist
Labels: :sparkles: enhancement

#55 [Design] 회원가입 화면 디자인을 수정했어요
  SixthSense/DesignSystem/Resources/Assets.xcassets/SignUp/sign_up_icon_1.imageset/01.svg
  SixthSense/DesignSystem/Resources/Assets.xcassets/SignUp/sign_up_icon_1.imageset/Contents.json
  SixthSense/DesignSystem/Resources/Assets.xcassets/SignUp/sign_up_icon_1.imageset/sign_up_icon_1.png
  SixthSense/DesignSystem/Resources/Assets.xcassets/SignUp/sign_up_icon_1.imageset/sign_up_icon_12x.png
  SixthSense/DesignSystem/Resources/Assets.xcassets/SignUp/sign_up_icon_1.imageset/sign_up_icon_13x.png
  SixthSense/DesignSystem/Resources/Assets.xcassets/SignUp/sign_up_icon_2.imageset/01_02.svg
  SixthSense/DesignSystem/Resources/Assets.xcassets/SignUp/sign_up_icon_2.imageset/Contents.json
  SixthSense/DesignSystem/Resources/Assets.xcassets/SignUp/sign_up_icon_2.imageset/icon_step-022x.png
  SixthSense/DesignSystem/Resources/Assets.xcassets/SignUp/sign_up_icon_2.imageset/icon_step-023x.png
  SixthSense/DesignSystem/Resources/Assets.xcassets/SignUp/sign_up_icon_2.imageset/icon_step-2.png
  SixthSense/DesignSystem/Resources/Assets.xcassets/SignUp/sign_up_icon_3.imageset/01_03.svg
  SixthSense/DesignSystem/Resources/Assets.xcassets/SignUp/sign_up_icon_3.imageset/Contents.json
  SixthSense/DesignSystem/Resources/Assets.xcassets/SignUp/sign_up_icon_3.imageset/icon_step-03_2x.png
  SixthSense/DesignSystem/Resources/Assets.xcassets/SignUp/sign_up_icon_3.imageset/icon_step-33.png
  SixthSense/DesignSystem/Resources/Assets.xcassets/SignUp/sign_up_icon_3.imageset/sign_up_icon_3.png
  SixthSense/DesignSystem/Resources/Assets.xcassets/SignUp/sign_up_icon_4.imageset/01_05.svg
  SixthSense/DesignSystem/Resources/Assets.xcassets/SignUp/sign_up_icon_4.imageset/Contents.json
  SixthSense/DesignSystem/Resources/Assets.xcassets/SignUp/sign_up_icon_4.imageset/icon_step-42.png
  SixthSense/DesignSystem/Resources/Assets.xcassets/SignUp/sign_up_icon_4.imageset/icon_step-46.png
  SixthSense/DesignSystem/Resources/Assets.xcassets/SignUp/sign_up_icon_4.imageset/sign_up_icon_4.png
  SixthSense/DesignSystem/Sources/AppTextField.swift
  SixthSense/DesignSystem/Sources/Assets/AppIcon.swift
  SixthSense/DesignSystem/Sources/Buttons/AppButton.swift
  SixthSense/DesignSystem/Sources/Buttons/SelectButton.swift
Labels: :art: UI

#56 [App] 회원가입 | 로그인 → 회원가입을 연결하고 내부 버튼 상태 로직을 개선했어요
  SixthSense/Account/Sources/SignIn/Domain/SignInUseCase.swift
  SixthSense/Account/Sources/SignIn/Presentation/SignInInteractor.swift
  SixthSense/Account/Sources/SignIn/Presentation/SignInRouter.swift
  SixthSense/Account/Sources/SignUp/Domain/Entities/SignUpPayload.swift
  SixthSense/Account/Sources/SignUp/Presentation/SignUpBuilder.swift
  SixthSense/Account/Sources/SignUp/Presentation/SignUpInteractor.swift
  SixthSense/Account/Sources/SignUp/Presentation/SignUpViewController.swift
Labels: :sparkles: enhancement

#57 [Network] Renewal Token API를 작성하고 기존 Provider를 개선하였어요
  SixthSense/Repository/Sources/AccessTokenService/AccessToken.swift
  SixthSense/Repository/Sources/AccessTokenService/AccessTokenService.swift
  SixthSense/Repository/Sources/AccessTokenService/AuthAPI.swift
  SixthSense/Repository/Sources/AccessTokenService/RenewalAuthToken.swift
  SixthSense/Repository/Sources/Network/APIError.swift
  SixthSense/Repository/Sources/Network/NetworkImpl.swift
  SixthSense/Repository/Sources/Network/Plugins/AccessTokenPlugin.swift
  SixthSense/Repository/Sources/Network/Plugins/RequestLoggingPlugin.swift
Labels: :sparkles: enhancement
